version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=Server=mssqlserver;Database=InginerieDB;User Id=SA;Password=Follyestepisica@12
    depends_on:
      - mssqlserver

  mssqlserver:
    image: samuelmarks/mssql-server-fts-sqlpackage-linux
    container_name: mssqlserver
    environment:
      SA_PASSWORD: "Follyestepisica@12"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    # command: ["/bin/bash", "-c", "/opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P 'Follyestepisica@12' -Q 'CREATE DATABASE InginerieDB'"]
    volumes:
      - ./df.bacpac:/opt/downloads/df.bacpac
    # command: ["/bin/bash", "-c", "dotnet /opt/sqlpackage/sqlpackage.dll /tsn:localhost /tu:SA /tp:'Follyestepisica@12' /A:Import /tdn:InginerieDB /sf:/opt/downloads/df.bacpac"]